### PR TITLE
Update to version 3.0.1

### PR DESCRIPTION
**Pull request by oplantalech**
Update made following the steps in: https://github.com/thehyve/cbioportal-docker/blob/master/docs/repo-maintenance.md

### CODE REVIEW

**Review by paulcwvandijk — APPROVED** [review]

**Comment by fedde-s** [comment]
Is there a need to implement this here? A setup based directly based on our setup for cBioPortal 2.x.x was released by Ino in cBioPortal 3.x.x itself, integrating feedback from other institutes. Unless there's a particular reason why we can't build on that, I'm hesitant to duplicate the logic here.

**Comment by oplantalech** [comment]
@fedde-s Is there also a cBioPortal image on Dockerhub where we can point to?

**Comment by fedde-s** [comment]
If the documentation is up-to-date, this should be it: https://github.com/cBioPortal/cbioportal/blob/v3.0.1/docs/docker/README.md#step-6---run-the-cbioportal-web-server

**Comment by fedde-s** [comment]
If not, I think we should see if we can fix it there.

**Pull request closed without merging**
