### PR TITLE
Update to v2.1.1+backport6012

### PR DESCRIPTION
**Pull request by oplantalech**
Version 2.1.1 with the commit fixing the issue in cBioPortal/cbioportal#5816 (from PR cBioPortal/cbioportal#6012)

### CODE REVIEW

**Comment by fedde-s** [comment]
Why would we want to release this again? Does it fix a major bug that (sometimes) occurs up when deploying v2.1.1 without the backport?

**Comment by oplantalech** [comment]
Sorry, yes: it fixes this bug cBioPortal/cbioportal#5816

**Comment by fedde-s** [comment]
And did you perform the manual tests in [repo-maintenance.md](https://github.com/thehyve/cbioportal-docker/blob/1ca45a7f687ada94fdb802707e12523c71f7875b/docs/repo-maintenance.md), at least for the components that may possibly be affected?

**Comment by oplantalech** [comment]
@fedde-s Yes. No changes in portal.properties, I've also inspected studies, everything works.

**Review by fedde-s — APPROVED** [review]
Backport and integration into Dockerfile look good, and since you saw the manual tests work, let's release it.

**Pull request merged**
