### PR TITLE
Update to v1.9.0

### PR DESCRIPTION
**Pull request by sandertan**
Also removed some configurable text that is specific for MSK and TCGA and clarified custom gene sets.

Diff between the resulting `portal.properties` files:
```diff
Sanders-MacBook-Pro:docker_cbioportal sander$ diff portal.properties-183 portal.properties-190 
3a4
> portal.version=${project.version}
22c23
< skin.example_study_queries=tcga\ntcga -provisional\ntcga -moratorium\ntcga OR icgc\n-"cell line"\nprostate mskcc\nesophageal OR stomach\nserous\nbreast
---
> skin.example_study_queries=
24c25
< skin.data_sets_footer=Data sets of TCGA studies were downloaded from Broad Firehose (http://gdac.broadinstitute.org) and updated monthly. In some studies, data sets were from the TCGA working groups directly.
---
> skin.data_sets_footer=
55c56
< skin.footer= | <a href="http://www.mskcc.org/mskcc/html/44.cfm">MSKCC</a> | <a href="http://cancergenome.nih.gov/">TCGA</a>
---
> skin.footer=
204a206,229
> 
> # labels to be displayed in oncoprint "Mutation color" menu for custom annotation of driver and passenger mutations in the oncoprint.
> # Set any of these properties to enable the respective menu options in oncoprint:
> # oncoprint.custom_driver_annotation.binary.menu_label=Custom driver annotation
> # oncoprint.custom_driver_annotation.tiers.menu_label=Custom driver tiers
> 
> # set this to false to disable the automatic selection of the custom driver/passenger mutations annotation (binary) in the oncoprint
> # when custom annotation data is present.
> # oncoprint.custom_driver_annotation.default=false
> 
> # set this to false to disable the automatic selection of the custom tiers in the oncoprint when custom annotation data is present. By default
> # this property is true.
> # oncoprint.custom_driver_tiers_annotation.default=false
> 
> # OncoKB and Hotspots are automatically selected as annotation source. If you want to disable them, set the following property to false. If you
> # want them to be selected only if there are no custom annotation driver and passenger mutations, type "custom".
> # oncoprint.oncokb_hotspots.default=custom
> 
> # Set this to true if you want to check the "hide Putative Passenger Mutations" checkbox by default.
> # oncoprint.hide_passenger.default=true
> 
> # Change this to custom JSON file (e.g. file:/<path>) to have a custom set of genes in query page.
> # JSON format should be in format of: https://github.com/cBioPortal/cbioportal-frontend/blob/master/src/shared/components/query/gene_lists.ts
> # querypage.setsofgenes.location =
Sanders-MacBook-Pro:docker_cbioportal sander$
```

### CODE REVIEW

**Comment by pieterlukasse** [comment]
@fedde-s please give this one some priority as we will need it for the training next week.

**Comment by fedde-s** [comment]
Will do; I'm working a commit that updates to v1.9.0 without switching to a less-robust patch file format, and separating out the documentation changes also proposed in this pull request.

**Comment by fedde-s** [comment]
The master branch will now install v1.9.0, as of commit f567aa15b2a4c9a8dd6e3cd1e2a10b718ad6f10b.

**Comment by fedde-s** [comment]
The main concern of updating to v1.9.0 has been solved in master, and I ported the remaining changes purposely proposed here to pull request #23 for discussion.

**Pull request closed without merging**
